@startuml
'https://plantuml.com/sequence-diagram

participant "main" as m
participant "etu : Etudiant" as E


create E
m -> E : new

m -> E : moyenne()
activate E

loop resultats.size()
    E -> Etudiant :moyenne(resultats.get(Matiere))
    activate Etudiant
    Etudiant --> E : moyenne
    deactivate Etudiant
end

E --> m : moyenne
deactivate E

@enduml