@startuml
'https://plantuml.com/class-diagram

class Etudiant{
 - resultats : HashMap<Matiere, List<double>>
    + Etudiant(Identite, Formation)
    + ajouter(Matiere, double: void
    + moyenne(Matiere): double
    + moyenne(): double
}

class Identite{
 - nom : String
 - prenom : String
 - NIP : String
    + Identite(String, String, String)
}

class Formation{
- idenitifiant : String
- coefficients : HashMap<Matiere, double>
    + Formation(String)
}

class Matiere{
 - nom : String
    + Matiere(String)
}

class Group{
- etudiants : HashMap<Etudiant, Formation>
    + Group(HashMap<Etudiant, Formation>)
}

Identite "1" <-- "1" Etudiant : identite
Etudiant "1" --> "*" Formation : formation
Etudiant "1" --> "*" Matiere : matiere
Formation "1" --> "*" Matiere : collectionMatiere
Group  "1" --> "*" Formation : formation
Group  "1" --> "*" Etudiant : etudiants

@enduml