@startuml
'https://plantuml.com/class-diagram

class Etudiant{
 - resultats : HashMap<Matiere, double>
    + Etudiant(Identite identite)
    + ajouter(String matiere, int note): void
    + moyenne(String matiere): double
    + moyenne(): double
}

class Identite{
 - nom : String
 - prenom : String
 - NIP : String
    + Identite(nom, prenom, NIP)
}

class Formation{
- idenitifiant : String
- coefficients : HashMap<Matiere, double>
    + Formation(identifiant)
}

class Matiere{
 - nom : String
    + Matiere(nom)
}

class Group{
- etudiants : HashMap<Etudiant, Formation>
    + Group(etudiants)
}

Identite "1" <-- "1" Etudiant : identite
Etudiant "1" --> "*" Formation : formation
Formation "1" --> "*" Matiere : collectionMatiere
Group  "1" --> "*" Formation : formation
Group  "1" --> "*" Etudiant : etudiants

@enduml